language: python
python:
  - '3.6'
install:
  - pip install pylint
  - pip install pytest
  - pip install pytest-cov
  - pip install codecov
script:
  - pylint source
  - pytest --cov=./ source
  - codecov
